name: release
on:
  push:
    tags:
      - "v*"
jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04
    name: ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: sudo apt update && sudo apt install -y libpango1.0-dev libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev
      - run: npm install
      - run: npm run tauri build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage

  build_macos:
    runs-on: macos-11
    name: macos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - run: npm run tauri build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/dmg/*.dmg
  build_windows:
    runs-on: windows-2019
    name: windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~\.cargo\bin\
            ~\.cargo\registry\index\
            ~\.cargo\registry\cache\
            ~\.cargo\git\db\
            src-tauri\target\
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - run: npm run tauri build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri\target\release\*.exe
            src-tauri\target\release\bundle\msi\*.msi
